/**
 * Build-time guard for the themes gallery (`docs/themes.mdx` / <ThemeGallery/>).
 *
 * This plugin does NOT expose the manifest via setGlobalData/usePluginData.
 * That mechanism bundles a plugin's entire payload into Docusaurus's shared
 * main.js runtime chunk - fetched on every page of the site, forever, since
 * usePluginData needs the data synchronously available everywhere. That is
 * fine for plugins/segments' small registry.json, but 124 inlined SVGs is a
 * different order of magnitude: measured, it added ~34KB gzip to main.js
 * itself, paid by every visitor on every page, not just /docs/themes.
 *
 * Instead, <ThemeGallery/> loads generated/themes.json itself via a plain
 * static import (see that component's own comment): webpack code-splits a
 * plain import into the page's own chunk without any special plugin
 * machinery, and being synchronous rather than a dynamic import(), it needs
 * no Loadable()/preloadAll trick to resolve during Docusaurus's SSR build
 * step either - the static HTML still has every theme inlined. This plugin
 * exists only to fail the build early with an actionable message if that file
 * is missing or malformed - the same guard plugins/segments' readRegistry
 * performs for its own generated file - rather than a deep webpack/React error
 * only surfacing once <ThemeGallery/> actually renders.
 */

const path = require('path');

const { readGeneratedJson } = require('../readGeneratedJson');

const MANIFEST_PATH = path.join(__dirname, '../../generated/themes.json');

function validateManifest() {
  const themes = readGeneratedJson(
    MANIFEST_PATH,
    'oh-my-posh-themes',
    'This file is generated by `npm run themes` (which shells out to an oh-my-posh binary on ' +
    'PATH), not written by hand. Run it, then re-run the website build.',
  );

  const seen = new Set();

  for (const entry of themes) {
    const valid = entry
      && typeof entry.name === 'string'
      && typeof entry.githubUrl === 'string'
      && typeof entry.svg === 'string';

    if (!valid) {
      throw new Error(
        `oh-my-posh-themes plugin: malformed entry in ${MANIFEST_PATH}: ${JSON.stringify(entry)}. ` +
        'Expected { name, githubUrl, svg }.',
      );
    }

    if (seen.has(entry.name)) {
      throw new Error(`oh-my-posh-themes plugin: duplicate theme name "${entry.name}" in ${MANIFEST_PATH}.`);
    }

    seen.add(entry.name);
  }
}

module.exports = function themesPlugin() {
  return {
    name: 'oh-my-posh-themes',

    async loadContent() {
      validateManifest();
    },
  };
};
