version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    groups:
      all:
        patterns:
        - "*"
    ignore:
      - dependency-name: "softprops/action-gh-release"
        # https://github.com/softprops/action-gh-release/issues/556
        versions: ["2.2.0"]

  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/src"
    target-branch: "main"
    schedule:
      interval: "daily"
    groups:
      minor-patch:
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
