scripts:
- name: Install APM
  command: apm install
  triggers:
  - session.create
- name: Restore apm.lock
  command: git restore apm.lock.yaml
  triggers:
  - session.create
- name: Install ast-grep-cli
  command: pip install ast-grep-cli
  triggers:
  - session.create
automation:
  auto_issue_session: true
  remote_control: true
