---
extends:
  - '@commitlint/config-conventional'
rules:
  body-max-line-length:
    - 2
    - always
    - 200
  type-enum:
    - 2
    - always
    - - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
      - theme
