config:
  MD013:
    line_length: 120
    code_blocks: false
  MD024: false
gitignore: true
ignores:
  - node_modules/
  - .github/agents/*.agent.md
  - .github/PULL_REQUEST_TEMPLATE.md
  - .agents/skills/ast-grep
  - .agents/skills/code-changes
  - .agents/skills/conventional-commit
  - .agents/skills/golang
  - .agents/skills/markdown
  - .agents/skills/powershell
  - .agents/skills/writing-clearly-and-concisely
  - .github/instructions/*
