name: 📖 Documentation
description: Suggest a change to the documentation
labels: ["📖 docs"]
assignees:
  - jandedobbeleer
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request this improvement!
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    id: enhancement-request
    attributes:
      label: What would you like to see changed/added?
      description: Try to give some examples or text to make it really clear!
      placeholder: Tell us what you would like to see!
      value: "This could change in the documentation!"
    validations:
      required: true
