name: 🤩 Enhancement
description: Suggest a change to an existing feature
labels: ["🤩 enhancement"]
assignees:
  - jandedobbeleer
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request this improvement!
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    id: enhancement-request
    attributes:
      label: What would you like to see changed?
      description: Try to give some examples to make it really clear!
      placeholder: Tell us what you would like to see!
      value: "This feature would benefit from this!"
    validations:
      required: true
