# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ohmyposh
      directives:
        description: Install Oh My Posh
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget
    # - resource: PSDesiredStateConfiguration/Script
    #   dependsOn:
    #     - ohmyposh
    #   id: fonts
    #   directives:
    #     description: Install Nerd Font
    #   settings:
    #     TestScript: return $false
    #     GetScript: oh-my-posh font install
  configurationVersion: 0.2.0
