export default {
  docs: [
    {
      type: "category",
      label: "Getting started",
      collapsed: false,
      link: {
        type: "generated-index",
        title: "Getting started",
        description: "Install Oh My Posh and set up your shell.",
        slug: "/",
      },
      items: [
        {
          type: "category",
          label: "Installation",
          collapsed: false,
          link: {
            type: "generated-index",
            title: "Installation",
            description: "Install Oh My Posh on Windows, macOS, or Linux.",
            slug: "/installation",
              },
          items: [
            "installation/windows",
            "installation/macos",
            "installation/linux",
          ],
        },
        "installation/fonts",
        "installation/prompt",
        "installation/customize",
        "installation/upgrade",
      ],
    },
    {
      type: "category",
      label: "Configuration",
      link: {
        type: "doc",
        id: "configuration/introduction",
      },
      // Split into what you have to understand and what you can switch on,
      // because a flat list of fifteen gave no clue which was which. Purely a
      // sidebar regrouping: every document keeps its id and therefore its URL,
      // which matters because this site has no client-redirects plugin, so a
      // moved file is a permanently dead link.
      items: [
        {
          type: "category",
          label: "Concepts",
          collapsed: false,
          link: {
            type: "generated-index",
            title: "Concepts",
            description: "The model a config is built from.",
            slug: "/configuration/concepts",
          },
          items: [
            "configuration/general",
            "configuration/block",
            "configuration/segment",
            "configuration/colors",
            "configuration/templates",
            "configuration/title",
          ],
        },
        {
          type: "category",
          label: "Features",
          collapsed: true,
          link: {
            type: "generated-index",
            title: "Features",
            description: "Optional behaviour you can turn on.",
            slug: "/configuration/features",
          },
          items: [
            "configuration/transient",
            "configuration/tooltips",
            "configuration/streaming",
            "configuration/secondary-prompt",
            "configuration/debug-prompt",
            "configuration/line-error",
            "configuration/data",
            "configuration/sample",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Segments",
      collapsed: true,
      link: {
        type: "doc",
        id: "segments/overview",
      },
      items: [
        {
          type: "category",
          label: "CLI",
          collapsed: true,
          link: {
            type: "generated-index",
            title: "CLI",
            description: "Segments for command-line tools and build systems.",
          },
          items: [
            "segments/cli/angular",
            "segments/cli/argocd",
            "segments/cli/aspire",
            "segments/cli/aurelia",
            "segments/cli/bazel",
            "segments/cli/buf",
            "segments/cli/bun",
            "segments/cli/claude",
            "segments/cli/cmake",
            "segments/cli/copilot",
            "segments/cli/copilot-cli",
            "segments/cli/deno",
            "segments/cli/docker",
            "segments/cli/firebase",
            "segments/cli/flutter",
            "segments/cli/gitversion",
            "segments/cli/gradle",
            "segments/cli/helm",
            "segments/cli/kubectl",
            "segments/cli/mvn",
            "segments/cli/nbgv",
            "segments/cli/nix-shell",
            "segments/cli/npm",
            "segments/cli/nx",
            "segments/cli/pnpm",
            "segments/cli/quasar",
            "segments/cli/react",
            "segments/cli/svelte",
            "segments/cli/talosctl",
            "segments/cli/taskwarrior",
            "segments/cli/tauri",
            "segments/cli/terraform",
            "segments/cli/ui5tooling",
            "segments/cli/umbraco",
            "segments/cli/unity",
            "segments/cli/uno",
            "segments/cli/xmake",
            "segments/cli/yarn",
            "segments/cli/zvm",
          ],
        },
        {
          type: "category",
          label: "Cloud",
          collapsed: true,
          link: {
            type: "generated-index",
            title: "Cloud",
            description: "Segments for cloud platforms and their CLIs.",
          },
          items: [
            "segments/cloud/aws",
            "segments/cloud/az",
            "segments/cloud/azd",
            "segments/cloud/azfunc",
            "segments/cloud/cds",
            "segments/cloud/cf",
            "segments/cloud/cftarget",
            "segments/cloud/gcp",
            "segments/cloud/pulumi",
            "segments/cloud/sitecore",
          ],
        },
        {
          type: "category",
          label: "Health",
          collapsed: true,
          link: {
            type: "generated-index",
            title: "Health",
            description: "Segments for health and fitness tracking.",
          },
          items: [
            "segments/health/nightscout",
            "segments/health/orthodoxcal",
            "segments/health/ramadan",
            "segments/health/strava",
            "segments/health/withings",
          ],
        },
        {
          type: "category",
          label: "Languages",
          collapsed: true,
          link: {
            type: "generated-index",
            title: "Languages",
            description: "Segments for programming language runtimes and versions.",
          },
          items: [
            "segments/languages/clojure",
            "segments/languages/crystal",
            "segments/languages/dart",
            "segments/languages/dotnet",
            "segments/languages/elixir",
            "segments/languages/fortran",
            "segments/languages/golang",
            "segments/languages/haskell",
            "segments/languages/java",
            "segments/languages/julia",
            "segments/languages/kotlin",
            "segments/languages/language",
            "segments/languages/lua",
            "segments/languages/mojo",
            "segments/languages/nim",
            "segments/languages/node",
            "segments/languages/ocaml",
            "segments/languages/perl",
            "segments/languages/php",
            "segments/languages/python",
            "segments/languages/r",
            "segments/languages/ruby",
            "segments/languages/rust",
            "segments/languages/swift",
            "segments/languages/v",
            "segments/languages/vala",
            "segments/languages/zig",
          ],
        },
        {
          type: "category",
          label: "Music",
          collapsed: true,
          link: {
            type: "generated-index",
            title: "Music",
            description: "Segments for now-playing music services.",
          },
          items: [
            "segments/music/lastfm",
            "segments/music/spotify",
            "segments/music/ytm",
          ],
        },
        {
          type: "category",
          label: "Source control",
          collapsed: true,
          link: {
            type: "generated-index",
            title: "Source control",
            description: "Segments for version control systems.",
          },
          items: [
            "segments/scm/dvc",
            "segments/scm/fossil",
            "segments/scm/git",
            "segments/scm/jujutsu",
            "segments/scm/mercurial",
            "segments/scm/plastic",
            "segments/scm/sapling",
            "segments/scm/svn",
          ],
        },
        {
          type: "category",
          label: "System",
          collapsed: true,
          link: {
            type: "generated-index",
            title: "System",
            description: "Segments for system and shell information.",
          },
          items: [
            "segments/system/battery",
            "segments/system/connection",
            "segments/system/executiontime",
            "segments/system/os",
            "segments/system/path",
            "segments/system/project",
            "segments/system/root",
            "segments/system/session",
            "segments/system/shell",
            "segments/system/status",
            "segments/system/sysinfo",
            "segments/system/text",
            "segments/system/time",
            "segments/system/upgrade",
            "segments/system/vimode",
            "segments/system/winget",
            "segments/system/winreg",
          ],
        },
        {
          type: "category",
          label: "Web",
          collapsed: true,
          link: {
            type: "generated-index",
            title: "Web",
            description: "Segments for web APIs and services.",
          },
          items: [
            "segments/web/brewfather",
            "segments/web/carbonintensity",
            "segments/web/http",
            "segments/web/ipify",
            "segments/web/nba",
            "segments/web/owm",
            "segments/web/todoist",
            "segments/web/wakatime",
          ],
        },
      ],
    },
    "studio",
    {
      type: "category",
      label: "Themes",
      collapsed: true,
      link: {
        type: "generated-index",
        title: "Themes",
        description: "Browse the bundled themes and share your own.",
        slug: "/themes-guide",
      },
      items: [
        "themes",
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsed: true,
      link: {
        type: "generated-index",
        title: "Guides",
        description: "Task-based guides beyond basic configuration.",
        slug: "/guides",
      },
      items: [
        "dsc",
        "advanced/mcp-server",
      ],
    },
    "faq",
    "migrating",
    {
      type: "category",
      label: "Contributing",
      collapsed: true,
      link: {
        type: "generated-index",
        title: "Contributing",
        description: "Help improve Oh My Posh.",
        slug: "/contributing",
      },
      items: [
        "contributing/started",
        "contributing/segment",
        "contributing/git",
        "contributing/plastic",
        "contributors",
      ],
    },
  ],
};
