name: Dependabot auto-merge
on:
  pull_request:
    types: [opened, reopened]

permissions:
    contents: write
    pull-requests: write

jobs:
  dependabot:
    uses: jandedobbeleer/workflows/.github/workflows/dependabot.yml@main
