name: Merge contributions PR
on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 👋
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - name: Check and merge ⛙
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const { repo: { owner, repo } } = context;
            const pr = context.payload.pull_request;

            if (pr.user.id !== 46447321) {
              console.log('Not an all-contributors pull request');
              return;
            }

            console.log(`Merging pull request: ${pr.html_url}`);
            await github.rest.pulls.merge({
              owner, repo,
              pull_number: pr.number,
              merge_method: "rebase",
            });
